[package]
name = "libcraft"
version = "0.0.1"
authors = ["Alexander Hayden", "Dylan Jones <dylanjones2011@gmail.com>"]
edition = "2018"

[dependencies]
#ctrlc = "3.1.3"
yaml-rust = "0.4.3"
warp = "0.2.2"
tokio = { version = "^0.2", features = ["macros"] }
